Features/add repositories
0MrCollBoy0/BankAPI pull request #2
Opened 2023-12-09 21:18 UTC by 0MrCollBoy0

2023-12-10 15:56 UTC, SimpleAleks requested changes

2023-12-10 15:56 UTC, SimpleAleks commented on src/Application/BankAPI.Application.AppServices/Contexts/Bill/Repositories/IBillRepository.cs
> +    /// <param name="cancellationToken"></param>
Пропущено описание параметра

2023-12-10 15:56 UTC, SimpleAleks commented on src/Application/BankAPI.Application.AppServices/Contexts/Bill/Services/IBillService.cs
> +    /// <param name="cancellationToken"></param>
Пропущен опиание

2023-12-10 15:56 UTC, SimpleAleks commented on src/Application/BankAPI.Application.AppServices/Contexts/User/Services/UserService.cs
> +        return await _repository.GetByIdAsync(id, cancellationToken);
Здесь точно нужен await?

2023-12-10 15:56 UTC, SimpleAleks commented on src/Application/BankAPI.Application.AppServices/Contexts/User/Services/UserService.cs
> +        return await _repository.GetAllAsync(cancellationToken);
Здесь нужен await?

2023-12-10 15:56 UTC, SimpleAleks commented on src/Contracts/BankAPI.Contracts/Contexts/User/CreateUserDto.cs
> +    public DateTime CreatedAt { get; set; }
Зачем при создании пользователя запрашивать даты создания и последней авторизации? Разве они не вычисляются со стороны бэка?

2023-12-10 15:56 UTC, SimpleAleks commented on src/Contracts/BankAPI.Contracts/Contexts/User/UpdateUserDto.cs
> +    public IEnumerable<BillDto> Bills { get; set; }
При обновлении пользователя нам нужны счета? Зачем и какие счета? Причём полные модели BillDto

2023-12-10 15:56 UTC, SimpleAleks commented on src/Contracts/BankAPI.Contracts/Contexts/User/UserDto.cs
> +    public IEnumerable<BillDto> Bills { get; set; }
BillDto содержит в себе модель UserDto. Я правильно понимаю, что здесь должна быть бесконечная рекурсия UserDto -> BillDto -> UserDto ...

2023-12-10 15:56 UTC, SimpleAleks commented on src/Hosts/BankAPI.Hosts.Api/Controllers/BillController.cs
> +public class BillController : ControllerBase
Добавь [ApiController]

2023-12-10 15:56 UTC, SimpleAleks commented on src/Hosts/BankAPI.Hosts.Api/Controllers/BillController.cs
> +public class BillController : ControllerBase
Посмотри как оформлен контроллер тут и сделай также
[AdvertController.cs](https://github.com/SimpleAleks/AdBoard/blob/main/src/Host/AdBoard.Host.Api/Controllers/AdvertController.cs)

2023-12-10 15:56 UTC, SimpleAleks commented on src/Hosts/BankAPI.Hosts.Api/Controllers/UserController.cs
> +    /// Получение всех списков Пользователей
Может "всех пользователей" или "списка пользователей"

2023-12-10 15:56 UTC, SimpleAleks commented on src/Hosts/BankAPI.Hosts.Api/Controllers/UserController.cs
> +        return Ok();
return Ok(null); Чтобы возвращался 204 No Content. а не 200 OK

2023-12-10 15:56 UTC, SimpleAleks commented on src/Infrastructure/BankAPI.Infrastructure.ComponentRegistrar/ComponentRegistrar.cs
> +
А BillService, BillRepository, DbContext?

2023-12-10 15:56 UTC, SimpleAleks commented on src/Infrastructure/BankAPI.Infrastructure.ComponentRegistrar/ComponentRegistrar.cs
> +        configuration.AddProfile<UserProfile>();
BillProfile?

2023-12-10 15:56 UTC, SimpleAleks commented on src/Infrastructure/BankAPI.Infrastructure.DataAccess/Contexts/Users/Repositories/UserRepository.cs
> +        return _repository.AddAsync(user, cancellationToken);
SaveChanges()? Во всём репозитории

2023-12-10 15:56 UTC, SimpleAleks commented on src/Infrastructure/BankAPI.Infrastructure.DataAccess/Contexts/Bill/Repositories/BillRepository.cs
> +        return _repository.AddAsync(bill, cancellationToken);
SaveChanges()? Во всё репозитории

2023-12-11 18:50 UTC, 0MrCollBoy0 commented on src/Application/BankAPI.Application.AppServices/Contexts/Bill/Repositories/IBillRepository.cs
> +    /// <param name="cancellationToken"></param>
Исправил

2023-12-11 18:50 UTC, 0MrCollBoy0 commented on src/Application/BankAPI.Application.AppServices/Contexts/Bill/Services/IBillService.cs
> +    /// <param name="cancellationToken"></param>
Исправил

2023-12-11 18:51 UTC, 0MrCollBoy0 commented on src/Application/BankAPI.Application.AppServices/Contexts/User/Services/UserService.cs
> +        return await _repository.GetByIdAsync(id, cancellationToken);
Убрал его

2023-12-11 18:51 UTC, 0MrCollBoy0 commented on src/Application/BankAPI.Application.AppServices/Contexts/User/Services/UserService.cs
> +        return await _repository.GetAllAsync(cancellationToken);
Убрал его

2023-12-11 18:51 UTC, 0MrCollBoy0 commented on src/Contracts/BankAPI.Contracts/Contexts/User/CreateUserDto.cs
> +    public DateTime CreatedAt { get; set; }
Удалил из CreateUserDto это поле

2023-12-11 18:52 UTC, 0MrCollBoy0 commented on src/Contracts/BankAPI.Contracts/Contexts/User/UpdateUserDto.cs
> +    public IEnumerable<BillDto> Bills { get; set; }
Удалил из этого дто это поле

2023-12-11 18:53 UTC, 0MrCollBoy0 commented on src/Contracts/BankAPI.Contracts/Contexts/User/UserDto.cs
> +    public IEnumerable<BillDto> Bills { get; set; }
Удалил из BillDto поле с пользователем

2023-12-11 18:53 UTC, 0MrCollBoy0 commented on src/Hosts/BankAPI.Hosts.Api/Controllers/BillController.cs
> +public class BillController : ControllerBase
Добавил ApiController и добавил rest для контроллера

2023-12-11 18:53 UTC, 0MrCollBoy0 commented on src/Hosts/BankAPI.Hosts.Api/Controllers/UserController.cs
> +    /// Получение всех списков Пользователей
Добавил ApiController и добавил rest для контроллера

2023-12-11 18:54 UTC, 0MrCollBoy0 commented on src/Hosts/BankAPI.Hosts.Api/Controllers/UserController.cs
> +        return Ok();
сделал

2023-12-11 18:55 UTC, 0MrCollBoy0 commented on src/Infrastructure/BankAPI.Infrastructure.ComponentRegistrar/ComponentRegistrar.cs
> +
Добавил связь сервиса и контекстов

2023-12-11 18:55 UTC, 0MrCollBoy0 commented on src/Infrastructure/BankAPI.Infrastructure.ComponentRegistrar/ComponentRegistrar.cs
> +        configuration.AddProfile<UserProfile>();
Добавил файл BillProfile и связал его в CommentRegistr

2023-12-11 18:56 UTC, 0MrCollBoy0 commented on src/Infrastructure/BankAPI.Infrastructure.DataAccess/Contexts/Users/Repositories/UserRepository.cs
> +        return _repository.AddAsync(user, cancellationToken);
Добавил в оба репозитория saveChanges

2023-12-11 18:56 UTC, 0MrCollBoy0 commented on src/Infrastructure/BankAPI.Infrastructure.DataAccess/Contexts/Bill/Repositories/BillRepository.cs
> +        return _repository.AddAsync(bill, cancellationToken);
Добавил

2023-12-13 19:58 UTC, SimpleAleks approved these changes

2023-12-14 13:20 UTC, merged